from collections.abc import Callable, Sequence
import enum


class FluidSource:
    @property
    def color(self) -> list[float]: ...

    @color.setter
    def color(self, arg: Sequence[float], /) -> None: ...

    @property
    def x(self) -> float: ...

    @x.setter
    def x(self, arg: float, /) -> None: ...

    @property
    def y(self) -> float: ...

    @y.setter
    def y(self, arg: float, /) -> None: ...

    @property
    def vx(self) -> float: ...

    @vx.setter
    def vx(self, arg: float, /) -> None: ...

    @property
    def vy(self) -> float: ...

    @vy.setter
    def vy(self, arg: float, /) -> None: ...

    @property
    def radius(self) -> float: ...

    @radius.setter
    def radius(self, arg: float, /) -> None: ...

    @property
    def active(self) -> bool: ...

    @active.setter
    def active(self, arg: bool, /) -> None: ...

    @property
    def mask(self) -> Mode: ...

    @mask.setter
    def mask(self, arg: Mode, /) -> None: ...

    @property
    def form(self) -> Form: ...

    @form.setter
    def form(self, arg: Form, /) -> None: ...

class Mode(enum.Flag):
    VELOCITY = 1

    DYE_ADDITIVE = 2

    DYE_REPLACE = 4

class Form(enum.Enum):
    CIRCLE = 0

    LINE = 1

    RADIAL = 2

def on_tick(callback: Callable | None) -> None: ...

def add_source(x: float, y: float, vx: float, vy: float, radius: float, color: Sequence[float]) -> FluidSource: ...

def remove_source(idx: int) -> None: ...

def get_source(idx: int) -> FluidSource: ...

def get_sources() -> list: ...

class Panel:
    def __init__(self) -> None: ...

    @property
    def title(self) -> str: ...

    @title.setter
    def title(self, arg: str, /) -> None: ...

    def add_button(self, id: str, label: str, on_click: Callable) -> None: ...

    def add_slider(self, id: str, label: str, default_val: float, min: float, max: float) -> None: ...

    def add_checkbox(self, id: str, label: str, default_val: bool) -> None: ...

    def add_drag_int(self, id: str, label: str, default_val: int) -> None: ...

    def sameline(self) -> None: ...

def set_panel(panel: Panel) -> None: ...

def open_file_dialog(filters: Sequence[tuple[str, str]] | None = None) -> str | None: ...

def save_file_dialog(filters: Sequence[tuple[str, str]] | None = None, default_name: str) -> str | None: ...
