"""Script panel UI"""

from collections.abc import Callable, Mapping, Sequence


class Panel:
    def __init__(self) -> None: ...

    @property
    def title(self) -> str: ...

    @title.setter
    def title(self, arg: str, /) -> None: ...

    def add_button(self, id: str, label: str, on_click: Callable[[Mapping[str, float | int | bool | Sequence[float]]], None]) -> None: ...

    def add_slider(self, id: str, label: str, default_val: float, min: float, max: float) -> None: ...

    def add_checkbox(self, id: str, label: str, default_val: bool) -> None: ...

    def add_drag_int(self, id: str, label: str, default_val: int) -> None: ...

    def sameline(self) -> None: ...

def set_panel(panel: Panel) -> None: ...

def set_widget_value(id: str, value: float | int | bool | Sequence[float]) -> None: ...

def set_widget_label(id: str, label: str) -> None: ...
