file(READ ${INPUT_FILE} CONTENT)
file(WRITE ${OUTPUT_FILE} "#pragma once\n")
file(APPEND ${OUTPUT_FILE} "#include <string_view>\n\n")
file(APPEND ${OUTPUT_FILE} "constexpr std::string_view ${VAR_NAME} = R\"(\n${CONTENT}\n)\";\n")
message(STATUS "Generated WGSL header: ${OUTPUT_FILE}")